### ISSUE TITLE
Front-end team: develop UI

### ISSUE THREAD

**Issue by yvah** [yvah/SwEng-group13#3]

**Comment by RoyHealy** [comment]
idealy we would like a 

- [ ]  Basic layout for the dashboard, separating input and output

- [ ]  input url for an open source repository (eg GitHub) that our Data extraction team can fetch data from

**Comment by RoyHealy** [comment]
- [ ] filter data from list editable by user

**Comment by yvah** [comment]
Moving the project onto different platform, no more classical UI.
